SELECT
    DISTINCT
    SAFE_CAST(id_estacao as INTEGER) id_estacao,
    SAFE_CAST(data_medicao as STRING) data_medicao,
    SAFE_CAST(coleta as STRING) tipo_coleta,
    SAFE_CAST(ponto as STRING) ponto_coleta,
    SAFE_CAST(data_inicio as STRING) data_inicio,
    SAFE_CAST(data_fim as STRING) data_fim,
    SAFE_CAST(ph as FLOAT64) ph,
    SAFE_CAST(temperatura_do_ar as FLOAT64) temperatura_ar,
    SAFE_CAST(temperatura_da_agua as STRING) temperatura_agua,
    SAFE_CAST(salinidade as STRING) salinidade,
    SAFE_CAST(oxigenio_dissolvido as STRING) oxigenio_dissolvido,
    SAFE_CAST(turbidez as STRING) turbidez,
    SAFE_CAST(disco_de_secchi as FLOAT64) disco_de_secchi,
    SAFE_CAST(profundidade_total as FLOAT64) profundidade_total,
    SAFE_CAST(profundidade_de_coleta as FLOAT64) profundidade_coleta,
    SAFE_CAST(coliformes_totais as STRING) coliformes_totais,
    SAFE_CAST(escherichia_coli as STRING) escherichia_coli,
    SAFE_CAST(nitrogenio_amoniacal as STRING) nitrogenio_amoniacal,
    SAFE_CAST(fosforo_total_mg_l as STRING) fosforo_total_mg_l,
    SAFE_CAST(fosforo_total_mg_kg as STRING) fosforo_total_mg_kg,
    SAFE_CAST(fosfato_total as STRING) fosfato_total,
    SAFE_CAST(nitrato as STRING) nitrato,
    SAFE_CAST(silica as STRING) silica,
    SAFE_CAST(sulfeto as STRING) sulfeto,
    SAFE_CAST(materia_organica as FLOAT64) materia_organica,
FROM `rj-rioaguas.saneamento_drenagem_staging.qualidade_agua`