version: 2
models :
  - name: nivel_reservatorio
    description: "**Descrição**: Dados de nível dos reservatórios de manejo de águas\
      \ pluviais do município do Rio de Janeiro.\n**Frequência de atualização**: 5\
      \ minutos\n**Cobertura temporal**: Desde 04/01/2021\n**Órgão gestor dos dados**:\
      \ RIO ÁGUAS\n**Publicado por**: Anderson Guilherme\n**Publicado por (email)**:\
      \ anderson.guilherme@cor.rio\n"
    columns:
      - name: primary_key
        description: Chave primária do dado em formato "[id_reserv]_AAAA-MM-DD_HH:MM:SS".
      - name: id_reservatorio
        description: Identificador do reservatório.
      - name: nome_reservatorio
        description: Nome do reservatório.
      - name: data_particao
        description: Data da medição no formato AAAA-MM-DD.
      - name: horario
        description: Hora da medicação no formato HH:MM:SS.
      - name: altura_agua
        description: Lâmina d'água no reservatório, em metros.
  - name: nivel_lamina_agua_via
    description: "**Descrição**: Dados do sensor de ultrasom para medir alagamento\
      \ em via pública.\n**Frequência de atualização**: Diário\n**Cobertura temporal**:\
      \ Desde 2022\n**Órgão gestor dos dados**: COR\n**Publicado por**: João Paulo\
      \ Fraga\n**Publicado por (email)**: jpfraga.rioaguas@gmail.com\n"
    columns:
      - name: primary_key
        description: Chave primária criada a partir da concatenação da coluna id_estacao
          e data_medicao. Serve para evitar dados duplicados. Formato [id_estacao]_AAAA-MM-DD_HH:MM:SS
      - name: id_estacao
        description: ID da estação.
      - name: data_particao
        description: Data da medição em formato AAAA-MM-DD.
      - name: horario
        description: Hora da medição em formato HH:MM:SS.
