version: 2
models :
  - name: nivel_reservatorio
    description: "**Descrição**: Dados de nível dos reservatórios de manejo de águas pluviais do município\
    do Rio de Janeiro.\n\
    **Frequência de atualização**: 5 minutos"
    columns:
      - name: primary_key
        description: Chave primária do dado em formato "[id_reserv]_AAAA-MM-DD_HH:MM:SS".
      - name: id_reservatorio
        description: Identificador do reservatório.
      - name: nome_reservatorio
        description: Nome do reservatório.
      - name: data_particao
        description: Data da medição no formato AAAA-MM-DD.
      - name: hora
        description: Hora da medicação no formato HH:MM:SS.
      - name: altura_agua
        description: Lâmina d'água no reservatório, em metros.          